FROM ubuntu:latest

RUN apt-get -y update
RUN apt-get install apt-utils
RUN apt-get install nano
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
RUN pip install jupyter
RUN pip install jupyterlab

EXPOSE 8888 22

WORKDIR /home

CMD ["jupyter", "lab", "--ip=*", "--allow-root"]