
FROM tensorflow/tensorflow:2.5.0-jupyter

RUN apt-get -y update
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip
#RUN pip install jupyter
RUN pip install jupyterlab

EXPOSE 8888 22

WORKDIR /


#CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
CMD ["jupyter", "lab", "--ip=*", "--allow-root"]